version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:176275544602:task-definition/digi-pms-gpd-td:1"
        LoadBalancerInfo:
          ContainerName: "digi-pms-gpd-container"
          ContainerPort: "9001"
        PlatformVersion: "LATEST"